### ISSUE TITLE
[Feature Request] Allow to specify different assaults to `watchedCustomServices`

### ISSUE THREAD

**Issue by carlos-rodrigues75** [codecentric/chaos-monkey-spring-boot#179]
Me and other devs from my company really like the library and would like to use it in some projects in the company, but reading the code we realised that the assaults are executed randomly across all watchers, don't having a more fine grained way to configure watchers.

For instance, it's not possible to configure a watcher for class A with only latency assault and class B with only Exception Assault, or even class B with latency assault as well but with different config params. 

The goal of this issue is to define a way to allow fine grained configurations. One possible solution is defined another property to specify a `List` of custom services, each object with their assault configurations. In these cases, the "global" assaults will not be triggered.

We were thinking about a good solution before starting any development, but we were wondering if this kind of behaviour would be great for the lib, or if this is not expected the lib to do.

If you guys liked the idea, we can discuss about the final solution. We are willing to implement it.

**Comment by maiksensi** [comment]
👋 Hey @carlos-rodrigues75,
thanks for reaching out with this. Glad to hear CMSB is of use to you. I think the general idea is great. Before going into development, let's ask @WtfJoke and @fletchgqc what they think. From my side 👍.

Before starting development, I think the details are important here. For example:
- How would the new API look like?
- Would existing endpoints change? (I guess so) 
- Would we have to do some refactoring before? 

Awesome that you're also offering to work this ❤️.

**Comment by fletchgqc** [comment]
In principle it sounds good. We should try to offer advanced functionality whilst keeping it simple to understand for people that are getting started. Great that you would build it.

I would like to hear more about your story. It sounds as if you considered using the tool, but didn't start because it doesn't have all the functionality you need. I would expect that the normal way things happen is that you get started, find you like the basics, but then you can't meet your use case.

I'm asking because I'm wondering about your use case. Could you tell us more about it? Most of the time people want to try one chaos experiment at a time, I guess that's why this request didn't come up yet. Why haven't you tried using the existing functionality of the tool before suggesting to expand it?

This might sound negative, but that's not my intention. I just want to understand how you got to where you are. I want to avoid implementing theoretically nice features which don't address a real use case.

**Comment by carlos-rodrigues75** [comment]
Hi @fletchgqc! I see your point and totally agree with you. 

Actually seems that we are trying to use the lib the wrong way. Researching about it we see the real use cases of the lib (and the integration with the chaos toolkit).

Our use case is that we have something like a "continuous test" that put some fake data in production, our point is to break this continuous flow using the lib, but in this case, we need a lot of things breaking randomly at the same time, asserting that these breaks have no impact. But I agree that this is not the best way to use the library and using the library + chaos toolkit to run chaos experiments is the right way to go.

We already started to do some POCs using the lib + chaos toolkit, but the need that all Spring beans must be non final is prevent us to use it. I know that since the code doesn't know which beans you'll need to run an experiment, the proxies are created to all beans and configurable at runtime.

Could you tell me whether there is a way to not enforce this? I couldn't figure out how to do this looking at the code. And if it needs some development to do, we can close this issue and discuss it in another one.

**Comment by carlos-rodrigues75** [comment]
@maiksensi @fletchgqc I'm closing this issue and I'll open another to discuss the behaviour that the application won't start when there are `final` beans in the `applicationContext`.
