### ISSUE TITLE
Feature request: random factor for runtime assault scheduling

### ISSUE THREAD

**Issue by mbouchenoire** [codecentric/chaos-monkey-spring-boot#181]
Hello,

I see two issues with the current runtime assault scheduling:

1. It's predictable since we know when the assaults will take place
2. Using Kubernetes when pods are started - almost- simultaneously (which happen the majority of the time) the assaults also happen - almost - simultaneously, which is not really what will happen without this library (even though it could, yes).

Edit : I know that it's possible to use SpEL to randomize the cron at startup, but it's still fixed when the application is started :(

Your thoughts on this?

**Comment by maiksensi** [comment]
Hey @mbouchenoire,
the described behaviour is partly intended. When this was implemented we wanted it to be predictable so correlating logs and traces would be easy. I see your point that there are use cases where you don't want it that predictable, but I guess you can help yourself with SpEL. 
For the second part, I normally keep CMSB deactivated when I start up my applications. When everything is settled and the app reaches steady state, I activate CMSB via `/enable`. @fletchgqc @WtfJoke what do you folks think? Is the immediate run of the assault a bug? I would say it is intended depending on your settings. Isn't the linux cron behaving the same way? 

But I also see your point @mbouchenoire if the app is pre-configured this is not very handy.

**Comment by WtfJoke** [comment]
Hi @mbouchenoire 

1. I agree with @maiksensi on first point, that the runtime assaults were made to be predictable (either using cron expressions or calling the `/assaults/runtime/attack` rest endpoint).

2. Usually I use CMSB also with the `/enable` endpoint (like maik described). 
The behaviour you describe shouldn't apply to Runtimeassaults (killApp/memory) in my opinion. 
As far as I am aware of these runtime assaults only trigger like described in 1. (therefore usually not on container/pod start). 

Can you share your application.properties/yaml (e.g CSM config)? 
Did you maybe confuse it with request assaults (latency, exception)? These could trigger on application start depending on your environment/config.

**Comment by mbouchenoire** [comment]
I understand that the current behavior is intented, but I'm advocating for an alternative, being *actual* chaos :).

On an other note, I don't know if it's related to this issue but I think it is : I'd to enable the KillApp and Memory assaults with different timings (even if not random). Currently, as far as I understand it you cannot schedule those 2 assaults independently, thus you cannot use them simultaneouslywith a cron (even with a random one).

**Comment by fletchgqc** [comment]
I must say, I quite like the idea of really being able to randomly kill the application. I wonder what the input for that would look like? Maybe the amount of times, on average, that the system should be killed per year? So 365 would be: about once per day. This would go in the direction of the original Netflix CM idea.

That said, I tend to do CE in controlled and limited timeframes. So I have no real use for it at the moment. I think it's worth considering, but after other more important tasks, like RestTemplate assault. This means basically: if someone creates a PR it could be done soon, otherwise it just has to sit on the backlog and we'll see if it ever becomes the top priority. That's just my opinion, of course.

On the other note, I believe you are right in your description of KillApp and Memory. Logically I think the ability to use them both fits into your train of thought - it's not necessary for controlled, short-term tests. This means, I understand where you are coming from and would consider this feature after the other feature.

**Comment by fletchgqc** [comment]
Also, if you want to continually and randomly kill applications, you need to build a mechanism that will keep the config when they restart. You could do this via property files. If you configured via Actuator, the config would be lost after the first restart.

One does begin to wonder whether this might be better achieved with a remote process (like Netflix did) rather than trying to build this in to every application. I think the summary of this for me is: interesting and even good ideas, but unlikely to get to the top of the backlog in the forseeable future. Feel free to send a PR.

**Comment by maiksensi** [comment]
@fletchgqc thanks for the thoughts and thanks @mbouchenoire for raising this. 
Let's focus on the three raised points:  

- Randomness: Is there any way you can build a script around your app that does randomly kill the app using the provided actuator rest endpoints? I guess that would give you way more flexibility. I am not even sure the cron killing makes to much sense in CMSB. CMSB should only take care of the kill, the timing should be provided from the outside, this way you can make use of composition. You mentioned SpEL, was that a possible suggestion how to implement this?
- App killed before it is up: tbh I don't really know how we could (in a sane way) decide when an app is "ready". If you think there is a good way, let us know and we can discuss a PR. 
As a workaround: Did you try "manually" enabling the monkey using the `/enable/ endpoint? 
- Using multiple assaults with different (cron) timings: good point. If you want to, please raise another issue with this, where we can discuss that. I think there's a valid use case for this. I am sure we can come up with something.

**Comment by mbouchenoire** [comment]
> Maybe the amount of times, on average, that the system should be killed per year? So 365 would be: about once per day.

I think this approach is a bit limiting, some people might want to test some "spikes" when the application gets killed multiple times a day. Here is a random cron that kills the application multiple times a day (I'm currently using it) :

`runtime-assault-cron-expression: ${random.int[0,59]} ${random.int[0,59]} */${random.int[1,7]} * * ?
`

> Also, if you want to continually and randomly kill applications, you need to build a mechanism that will keep the config when they restart

This is not necessary if you use a random cron (like shown previously).

> App killed before it is up: tbh I don't really know how we could (in a sane way) decide when an app is "ready".

Could we use the Spring context events as shown [here](https://www.baeldung.com/spring-context-events) ?

> Using multiple assaults with different (cron) timings: good point. If you want to, please raise another issue with this, where we can discuss that. I think there's a valid use case for this. I am sure we can come up with something.

I might get on this, with these new properties :
  - `kill-application-cron`
  - `memory-cron`
