### ISSUE TITLE
Upgrade to JDK11

### ISSUE THREAD

**Issue by WtfJoke** [codecentric/chaos-monkey-spring-boot#235]
As more and more people are on JDK11 we could update our minimum required java version to 11.

According to the [recent 2021 jvm eco system report from snyk ](https://snyk.io/jvm-ecosystem-report-2021/) 62% use JDK 11 in production whereas 60% still use JDK 8 in production.

Not sure if we should do that already with the next release 2.5.2 or in a later release.

I prepared already the few changes needed, see https://github.com/WtfJoke/chaos-monkey-spring-boot/tree/upgradeJdk

**Comment by checketts** [comment]
What benefits would requiring JDK 11 provide? I'm not opposed, just want to understand if there are specific benefits. Since this project is for 'Spring Boot' it seems like we would want to follow their baseline.

About 20% of the projects that I am paid to work on are on JDK 8. (Admittedly we are slowly upgrading those)

**Comment by WtfJoke** [comment]
I guess the benefit would be, that we could use jdk 11 features in our code.

Allthough as a library users perspective it makes more sense to stay on jdk 8 (as you say some folks are still on jdk 8).

**Comment by WtfJoke** [comment]
I'll close this, lets stick to the baseline of spring boot.
