### ISSUE TITLE
Hi, Is there any nice plan to user on distributed system?

### ISSUE THREAD

**Issue by kobezhangjian** [codecentric/chaos-monkey-spring-boot#311]
Hi, how to user on distributed system

**Comment by WtfJoke** [comment]
HI @kobezhangjian 
I dont understand your request fully.

Do you mean if its possible to use it on a multi instance environment? If so yeah that works, but you need to take care that you disable/enable it on all instances at the same time so that you dont have 50% Chaos and 50% non Chaos.

Another way is to use the feature toggle support of unleashed. There you can enable/disable Chaos Monkey for all instances at the same time with separate rules.
