### ISSUE TITLE
Watcher for outgoing Rest-Calls (Template)

### ISSUE THREAD

**Issue by ChristianLangmann** [codecentric/chaos-monkey-spring-boot#93]
Instead of watching components that implement a function and assaulting it, watch for outgoing calls (using RestTemplate) and assault this.

**Comment by haridevelops** [comment]
what exactly needs to be fixed ? can you elaborate ?

**Comment by elijah-pl** [comment]
I think the goal should be achieved by writing an interceptor that will be injected into the existing `RestTemplate` bean and randomly return different responses (timeout, internal server error, ok etc.) or introduce delays.

```java
@Bean
@Primary // <- Not sure if this will be needed, probably not
@ConditionalOnBean(RestTemplate.class)
@ConditionalOnProperty(..) // <- Check if RestTemplate assaulting is enabled
public RestTemplate restTemplate(RestTemplate restTemplate) {
    restTemplate.getInterceptors().add(new ChaosMonkeyInterceptor(..));
    return restTemplate;
}
```
If @maiksensi is OK with this solution, I would like to prepare a MR for this.

**Comment by maiksensi** [comment]
Hey @haridevelops and @elijah-pl,

thanks for your interest in this issue. It is highly appreciated. Currently, Chaos Monkey for Spring Boot (CMSB) is able to assault several annotations one can use. Such as `@Controller`, or `@Service`. Assaulting outgoing calls (where `@RestTemplate` is used) are not part of the possible classes that can be assaulted. 

However, so far we did not discuss the exact scope of that feature. 

@elijah-pl your propsal sounds interesting. I wonder whether it is possible to match "all possible" use cases with that? Because `RestTemplate` is not an Annotation. `RestTemplate` can be used with or without Autowiring. I take it that the pseudo code above would only work for cases where you would do something like this: 

```
....
@Autowired
RestTemplate restTemplate;
...
```

What about cases where a `RestTemplate` is instantiated like this: 

```
....
public void someMethod() {
    RestTemplate restTemplate = new RestTemplate();
}
```

**Comment by haridevelops** [comment]
We can create something like RestCommonClient.java which can be inherited which class wants to do a rest call.

So RestTemplate will a class level variable of RestCommonClient. hence can be utilised all across.

For your case like new RestTemplate() scenario, 
There won't be a much of code change than referencing the right object from parent .

**Comment by haridevelops** [comment]
Like how we add an Error handler for a  RestTemplate.

All the exceptions and intercepting can be done at one place which can utilized all across.

**Comment by elijah-pl** [comment]
@maiksensi As far as I know, AspectJ supports constructor interception, so solution can be extended with aspect that will inject `ChaosMonkeyInterceptor` into manually created instances of `RestTemplate`

**Comment by maiksensi** [comment]
@elijah-pl thanks for pointing that out. I haven't done too much with AspectJ so far. Anyways, @WtfJoke and I will meet on Thuesday and there we can discuss the feature in more details and what the technical implementation could look like. I just want to make sure theres no need to change anything for a possible users (for example using rest template in a specific way is not a good solution imho). 

If you want to hack something together so we can have a look at it on Thuesday that would be great. To me it seems we need to hack a bit and see how it goes to come up with a better solution then if needed.

**Comment by WtfJoke** [comment]
For clarification, we meet on Thursday Evening (CEST) :)

**Comment by elijah-pl** [comment]
@maiksensi @WtfJoke There are good chances that I'll be able to participate on Thursday. Reach me on FB.

**Comment by maiksensi** [comment]
Unfortunately we didn't get to discuss the topic last week. I will remove the hacktoberfest label for now, as I am not sure expectations are clear. To summarize I would expect the following: 

- It does not matter to a user whether `RestTemplate` is added as a Bean, or a custom class or directly instantiated 
- A user should thus not need to change existing code in order to attack 

I will have a look on how one of our teams uses `RestTemplate` currently, and maybe we can begin with that use case.

**Comment by sanha** [comment]
The goal of this issue sounds nice 👍 

I applied CM4SB to my application and enjoyed it, but realized soon that the assaults can't attack the http call itself. Therefore, I can't verified that my timeout settings and circuit breakers work well with it. Because of this, I made an empty service just for the assault injection and call it in every remote calls. If this feature is implemented, people like me don't need to do this stuffs manually.

BTW, do you have any plan to supports `WebClient` well? (I'm using `WebClient` instead of `RestTemplate` actually...) Should it be another issue?

Many thanks :)

**Comment by fletchgqc** [comment]
Regarding WebClient: Spring actually state in their [doco](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/client/RestTemplate.html) that RestTemplate will be deprecated in future and that you should use WebClient. Nevertheless, I think there are probably a lot of people still using RestTemplate and it's worth implementing something. We should do something for WebClient too, let's handle that as a separate issue, to keep this task small and doable.

**Comment by fletchgqc** [comment]
I had a go at this today. Have a look at: https://github.com/fletchgqc/chaos-monkey-spring-boot/pull/2/files.

There I have demonstrated a POC for both RestTemplate and WebClient. The RestTemplate part is done with an interceptor as suggested by @elijah-pl. As you can see from the tests, it "works".

However, I have not managed to achieve the AOP part yet.

I agree with @maiksensi's two points, it should work without any change to existing code (this is one of the major benefits of CMSB in general) and the ideal solution would work for all cases.

Bearing that in mind, here is what I figured out so far about the AOP implementation:

### AspectJ
So far we only use Spring AOP, no direct AspectJ. It would be ideal to continue just using one technology, for simplicity's sake. However, as pointed out above, Spring AOP doesn't support constructor pointcuts, and it if I understood [the documentation](https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#aop-pointcuts) correctly, it only works on Spring Beans. Since a class created manually is not a Spring Bean, I guess we have to use AspectJ.

### RestTemplate
Here I see two alternatives: intercept the constructor, or intercept the call to doExecute(), which is what all the overloaded methods eventually call. The former option will probably more performant. The implementation we choose should give us the chance to inspect the request (at least the URL) and decide whether to act. Although I wouldn't implement that yet, in future we will surely want to give the user the chance to assault calls to backend1 but not to backend2.

### WebClient
Here, we have a similar problem as with RestTemplate. It's easy to configure a kind of filter using the WebClient.Builder, however, the user can also call WebClient.create() and bypass that. This is explained quite nicely [in the documentation](https://docs.spring.io/spring-boot/docs/2.1.3.RELEASE/reference/html/boot-features-webclient.html#boot-features-webclient-customization). In my code you see a workaround which I found: if you call webClient.mutate() then you are given a WebClient.Builder which you can manipulate, configured in accordance with the webClient. Or just intercept calls to WebClient.create and return our own WebClient with interceptor in it.

I hope all that information is not too overwhelming. I welcome comments on the code I've written so far and help for the remaining AOP part. If someone can just demonstrate how to get AspectJ up and running in our project with a basic pointcut for RestTemplate creation and test, that would probably be enough to get me going towards a solution.

**Comment by WtfJoke** [comment]
Nice writeup @fletchgqc, the work done in the pull-request looks already promising. 


> Spring AOP doesn't support constructor pointcuts, and it if I understood [the documentation](https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#aop-pointcuts) correctly, it only works on Spring Beans.

Yes, I understand it like that as well

> Since a class created manually is not a Spring Bean, I guess we have to use AspectJ.

I am not sure if its worth replacing Spring AOP with AspectJ "just" to have the Non-Bean Instantiation covered.  

Personally im not very familiar with AspectJ but [it sounds like, it doesnt support Runtime-Weaving](https://www.baeldung.com/spring-aop-vs-aspectj#summary) (like Spring AOP does).  

Assuming we go for AspectJ... after reading [this part](https://www.baeldung.com/spring-aop-vs-aspectj#5-simplicity) im not even sure if we then just could add chaos monkey as dependency to an app and it works without any recompilation of that app (since aspectj have its own compiler,debugger etc..). And that would be a huge negative point.

I will try to read a bit more into AspectJ.

**Comment by fletchgqc** [comment]
> I am not sure if its worth replacing Spring AOP with AspectJ...

Well, rather adding than replacing. As the Baelding article you linked to says:

> Best of Both: Both of these frameworks are fully compatible with each other. We can always take advantage of Spring AOP whenever possible and still use AspectJ to get support of joinpoints that aren't supported by the former.

**Comment by checketts** [comment]
@fletchgqc Its been a year. Have you done any further work with WebClient? I looked at your PR https://github.com/fletchgqc/chaos-monkey-spring-boot/pull/2/files to see if there is any code I could 'borrow' But didn't see any support for adding/removing it using the typical chaos monkey configs.
